# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20170703_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='users_with_tag',
            new_name='followers_count',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
