# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 21:47
from __future__ import unicode_literals

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=common.models.make_user_image_path)),
                ('reputation', models.BigIntegerField(default=0)),
                ('gold_badges', models.IntegerField(default=0)),
                ('silver_badges', models.IntegerField(default=0)),
                ('bronze_badges', models.IntegerField(default=0)),
                ('answers_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User profiles',
                'verbose_name': 'User profile',
            },
        ),
    ]
