# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 21:47
from __future__ import unicode_literals

import common.utilities
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='unnamed', max_length=20)),
                ('description', models.TextField(default='')),
                ('created_date', models.DateField(auto_now=True)),
                ('questions_count', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=common.utilities.get_null_user, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
